---

- name: setup forwarding on gateway
  hosts: gateway[0]
  become: true
  roles:
    - forwarding
  tags:
    - forwarding

- name: setup default route on workers
  hosts: ceph_cluster
  become: true
  roles:
    - default-gateway
  tags:
    - default-gateway

- name: setup pre-requisites
  hosts: all
  become: true
  roles:
    - common
  tags:
    - common

- name: install docker in iran
  hosts: docker-iran
  become: true
  roles:
    - docker
  vars:
    docker_iran: true
  tags:
    - docker

- name: install docker
  hosts: docker
  become: true
  roles:
    - docker
  tags:
    - docker

- name: configure gateway routing
  hosts: gateway[0]
  become: true
  roles:
    - iptables
    - haproxy
  tags:
    - haproxy
    - iptables
